name: Sync JSON to cuckoo-clock-site

on:
  push:
    branches:
      - main
    paths:
      - "bird_data.json"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cuckoo-clock
        uses: actions/checkout@v3
        with:
          path: cuckoo-clock

      - name: Checkout cuckoo-clock-site
        uses: actions/checkout@v3
        with:
          repository: dnywh/cuckoo-clock-site
          token: ${{ secrets.PAT_TOKEN }}
          path: cuckoo-clock-site

      - name: Copy JSON file
        run: |
          cp cuckoo-clock/bird_data.json cuckoo-clock-site/src/data/bird_data.json

      - name: Commit and push if changed
        run: |
          cd cuckoo-clock-site
          git config user.name dnywh
          git config user.email "3104761+dnywh@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update birds.json"; git push)
