name: Sync Bird Data and Images

on:
  push:
    branches:
      - main
    paths:
      - "bird_data.json"
      - "birds/**/*.jpg"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout cuckoo-clock
        uses: actions/checkout@v4
        with:
          path: cuckoo-clock

      - name: Checkout cuckoo-clock-site
        uses: actions/checkout@v4
        with:
          repository: dnywh/cuckoo-clock-site
          token: ${{ secrets.PAT_TOKEN }}
          path: cuckoo-clock-site

      - name: Copy JSON file
        run: |
          cp cuckoo-clock/bird_data.json cuckoo-clock-site/src/data/bird_data.json

      - name: Copy JPG files
        run: |
          mkdir -p cuckoo-clock-site/public/images
          find cuckoo-clock/birds -name "*.jpg" -exec cp {} cuckoo-clock-site/public/images/ \;

      - name: Commit and push if changed
        run: |
          cd cuckoo-clock-site
          git config user.name dnywh
          git config user.email "3104761+dnywh@users.noreply.github.com"
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "Updated bird data and images"; git push)
